# Generated by Django 4.2.4 on 2023-08-31 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("motorcycles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productos",
            name="fecha_registro",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
