# Generated by Django 4.2.4 on 2023-08-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("motorcycles", "0003_categorias_alter_productos_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productos",
            name="categoria",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Categorias",
        ),
    ]
