# Generated by Django 4.2.4 on 2023-09-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("motorcycles", "0006_clientes_motos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientes",
            name="id",
        ),
        migrations.RemoveField(
            model_name="motos",
            name="id",
        ),
        migrations.AlterField(
            model_name="clientes",
            name="documento",
            field=models.CharField(
                max_length=10, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="motos",
            name="placa",
            field=models.CharField(
                max_length=6, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
