# Generated by Django 4.2.3 on 2023-09-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("motorcycles", "0007_remove_clientes_id_remove_motos_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientes",
            name="documento",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
